#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Change the DHCP timeout to a 60 second value.
sed -i "s/timeout.*/timeout 60;/g" /etc/dhcp/dhclient.conf
