#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# downgrade cloud-init
# see https://bugs.centos.org/view.php?id=15629
yum downgrade -y cloud-init-0.7.5-10.el7.centos.2

exit 0
